### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by brettz9** [nolanlawson/node-websql#16]
Hi,

I'm finding your project very helpful for IndexedDBShim, thank you.

I think I'm in need of configuring the [transaction duration](https://github.com/nolanlawson/node-websql/blob/7559b390f4aa10ccd0309e20282af0ab08d11df5/lib/websql/WebSQLDatabase.js#L60-L63). You use `immediate` there which is reasonable, but I'm wondering whether you'd be open to adding a means for the user to provide a callback which would allow continuing on only when it invoked a continuation callback supplied to it, e.g., so as to allow an extra-long transaction which could handle a rollback that included a set of SQL statements which were added over a longer period of time.

(And while we're discussing configuring the SQLite behavior, FYI, I made my own light SQLiteDatabase class which just adds the ability to alter SQLite's `busyTimeout`, `trace`, and `profile` [config](https://github.com/mapbox/node-sqlite3/wiki/API#databaseconfigureoption-value) which I mention in case you felt like exposing this as it is not really a new API either per se, but this was easy enough for me to implement without mucking around with your code.)

**Comment by nolanlawson** [comment]
To be honest I'm not interested in added behavior that differs from the original WebSQL spec (or the de-facto implementation in Chrome/Safari); I just want this to serve as a pure Node implementation. I believe using anything other than `immediate` (or `setTimeout` etc.) would cause deviations from the spec.

OTOH you are welcome to extend this project and write a new one that implements custom behavior on top of it, and I would encourage you to do so. :) Unless I misunderstood your request, in which case please let me know.

**Comment by brettz9** [comment]
Sure, fair enough! And thanks again for the project!
