### ISSUE TITLE
Mention, if not workaround, surfaced node-sqlite3 database restrictions

### ISSUE THREAD

**Issue by brettz9** [nolanlawson/node-websql#19]
The [WebSQL spec](https://www.w3.org/TR/webdatabase/#dom-opendatabase), indicates that any string, including the empty string, can be used (and ought to be treated case-sensitively):

> All strings including the empty string are valid database names. Database names must be compared in a case-sensitive manner.
>
> Implementations can support this even in environments that only support a subset of all strings as database names by mapping database names (e.g. using a hashing algorithm) to the supported set of names.

However, `node-sqlite3` databases, according to [the API](https://github.com/mapbox/node-sqlite3/wiki/API) allow the following:

> Valid values are filenames, ":memory:" for an anonymous in-memory database and an empty string for an anonymous disk-based database. Anonymous databases are not persisted and when closing the database handle, their contents are lost.

Filenames do not necessary allow for every type of string, though I suppose it will vary by platform. In addition, as per the above, `node-sqlite3` interprets an empty string and ":memory:" in a special manner which at the least may be unexpected for users.

I am guessing you may not wish to escape some or all database names in order to accommodate this (since the file names will be less readable), so if that is the case, my suggestion is to at least document what will happen.

A similar warning should perhaps be added about NULL bytes when making [`exec`](https://github.com/mapbox/node-sqlite3/wiki/API#databaseexecsql-callback) calls as this restriction is not listed in the WebSQL spec nor SQLite.

While I'm asking questions, I also wonder what you think of using [sqlite3.cached.Database](https://github.com/mapbox/node-sqlite3/wiki/Caching) (though note it doesn't cache empty string or ":memory:" databases).

**Comment by nolanlawson** [comment]
Thanks for the explanation! I think I'm fine with non-conformance in this case since it's so edge-casey. But yes it should probably be documented in the README. Happy to take a PR. :)
