### ISSUE TITLE
Support the WebSQL synchronous API

### ISSUE THREAD

**Issue by brettz9** [nolanlawson/node-websql#23]
I know you're probably too busy and possibly not interested in this, but I thought I'd at least record a possible wish here for support of the synchronous API (which was spec'd but apparently not implemented, at least in Chrome or Safari apparently).

See https://github.com/axemclion/IndexedDBShim/issues/296 for one possible use case.

**Comment by nolanlawson** [comment]
True, I don't have much interest in implementing the synchronous API. I agree it may be interesting for some use cases though, so possibly a fork or PR is in order. :)
