### ISSUE TITLE
SQL.js

### ISSUE THREAD

**Issue by brodybits** [nolanlawson/node-websql#27]
I have a client who  is interested in using Web SQL API for testing in a browser, without need for the Cordova framework itself. Built-in Web SQL is not suitable for reasons such as:
- no support for numbered parameters (`?1`, `?2`, ...)
- deprecation and removal is wanted (<https://github.com/WICG/interventions/issues/46>)
- some other features such as FTS5, R-Tree, and JSON1 are not supported

I think the obvious solution is to use SQL.js.

While the implementation should be straightforward I think it would be nice to avoid duplicated efforts if possible.

**Comment by nolanlawson** [comment]
The goal of `node-websql` is to implement the WebSQL API. I'm not really maintaining it anymore or looking to move it in another direction, but if you would like to use `node-websql` to implement what you're talking about, it should be possible. Using the plugin API, you can implement your own SQLite bindings under the hood (or mock it out using SQL.js). Not sure if that helps, but those are my current goals for the project… also feel free to fork. :)
