### ISSUE TITLE
Prepare statements under the hood

### ISSUE THREAD

**Issue by nolanlawson** [nolanlawson/node-websql#3]
Given that most people are probably not dynamically generating SQL queries, but are rather using a small number of queries and then using `?` to fill in the arguments, we can probably get away with just keeping a global cache of prepared statements, In principle this should speed it up pretty significantly, at the cost of increased memory usage.

**Comment by nolanlawson** [comment]
I think this might be a bad idea, since it has to be done via heuristics. Closing.

**Comment by tslater** [comment]
Currently, there isn't any support for prepared statements, and it would fall under non-goals, is that correct?
